import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Coagentix Terms of Service — the rules governing your use of the platform.",
  alternates: { canonical: "https://coagentix.app/terms" },
};

const EFFECTIVE = "19 June 2026";

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-20">
      <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">Effective date: {EFFECTIVE}</p>

      <div className="mt-10 space-y-10 text-base leading-7">
        <Section title="1. Acceptance">
          <p>
            By accessing or using Coagentix (&quot;Service&quot;), you agree to be bound by these Terms. If
            you do not agree, do not use the Service.
          </p>
        </Section>

        <Section title="2. Use of the Service">
          <ul className="list-disc pl-5 space-y-2">
            <li>You must be at least 13 years old (or the minimum age of digital consent in your jurisdiction).</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>You may not use the Service to generate content that is illegal, harmful, abusive, or violates the policies of the underlying AI providers.</li>
            <li>You may not reverse engineer, scrape, or abuse the Service&apos;s APIs beyond their intended use.</li>
          </ul>
        </Section>

        <Section title="3. API keys & provider policies">
          <p>
            When you provide API keys for third-party providers (Anthropic, Google, etc.), you remain
            responsible for complying with those providers&apos; terms of service. Coagentix stores your
            keys encrypted and forwards them only to the provider you select for each request.
          </p>
        </Section>

        <Section title="4. Subscription & billing">
          <p>
            Paid plans are billed in advance on a monthly cycle. Cancellation takes effect at the end
            of the current period. We do not offer refunds for partial months except where required by
            law.
          </p>
        </Section>

        <Section title="5. Intellectual property">
          <p>
            Content you input (&quot;Input&quot;) remains yours. Output generated by AI models (&quot;Output&quot;) is
            subject to each provider&apos;s terms regarding ownership. Coagentix claims no ownership over
            your Input or Output.
          </p>
          <p className="mt-3">
            Coagentix&apos;s platform, branding, and code are owned by Coagentix and protected by
            intellectual property law.
          </p>
        </Section>

        <Section title="6. Disclaimer of warranties">
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind, express or implied. We do
            not warrant that the Service will be error-free, uninterrupted, or that AI outputs will be
            accurate or complete.
          </p>
        </Section>

        <Section title="7. Limitation of liability">
          <p>
            To the maximum extent permitted by law, Coagentix shall not be liable for any indirect,
            incidental, special, or consequential damages arising from your use of the Service.
            Our total liability shall not exceed the amount you paid us in the 12 months preceding the
            claim.
          </p>
        </Section>

        <Section title="8. Termination">
          <p>
            We may suspend or terminate your access for violations of these Terms or applicable law.
            You may delete your account at any time via Settings.
          </p>
        </Section>

        <Section title="9. Governing law">
          <p>
            These Terms are governed by the laws of Thailand. Disputes shall be resolved in the courts
            of Thailand.
          </p>
        </Section>

        <Section title="10. Changes">
          <p>
            We may update these Terms. We will notify you of material changes via the platform or
            email. Continued use constitutes acceptance of the updated Terms.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            Questions about these Terms?{" "}
            <a href="mailto:legal@coagentix.app" className="text-primary hover:underline">
              legal@coagentix.app
            </a>
          </p>
        </Section>
      </div>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-semibold tracking-tight mb-3">{title}</h2>
      {children}
    </section>
  );
}
