"use client";

// ── GitHub Panel (Phase 4) ────────────────────────────────────────────────────
// Connect, clone, switch branches, commit, push, create PRs.
// All Git ops go through the /api/github proxy (token stays in httpOnly cookie).

import { useEffect, useState } from "react";
import {
  Github, GitBranch, GitCommit, GitPullRequest,
  Loader2, LogOut, RefreshCw, ShieldAlert,
  Check, Plus, ExternalLink,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { useCocodeIDEStore } from "@/store/cocode-ide-store";

export function GitHubPanel() {
  const github = useCocodeIDEStore((s) => s.github);
  const connectGitHub = useCocodeIDEStore((s) => s.connectGitHub);
  const disconnectGitHub = useCocodeIDEStore((s) => s.disconnectGitHub);
  const listRepos = useCocodeIDEStore((s) => s.listRepos);
  const loadRepo = useCocodeIDEStore((s) => s.loadRepo);
  const switchBranch = useCocodeIDEStore((s) => s.switchBranch);
  const pushToGitHub = useCocodeIDEStore((s) => s.pushToGitHub);
  const createGitBranch = useCocodeIDEStore((s) => s.createGitBranch);
  const openPR = useCocodeIDEStore((s) => s.openPR);
  const cloneProgress = useCocodeIDEStore((s) => s.cloneProgress);
  const allFiles = useCocodeIDEStore((s) => s.allFiles);
  const projectName = useCocodeIDEStore((s) => s.projectName);

  const [repoInput, setRepoInput] = useState("");
  const [commitMsg, setCommitMsg] = useState("");
  const [newBranch, setNewBranch] = useState("");
  const [prTitle, setPrTitle] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [committing, setCommitting] = useState(false);
  const [creatingBranch, setCreatingBranch] = useState(false);
  const [prUrl, setPrUrl] = useState<string | null>(null);
  const [lastCommitUrl, setLastCommitUrl] = useState<string | null>(null);

  const files = allFiles();
  const dirtyFiles = files.filter((f) => f.dirty).map((f) => f.path);

  // Repos may be stale/empty when the panel opens (e.g. connection restored
  // from cookie before this panel mounted) — fetch once when connected.
  useEffect(() => {
    if (github.connected && github.repos.length === 0) void listRepos();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- run on connect only
  }, [github.connected]);

  async function handleLoadRepo(fullName?: string) {
    const clean = (fullName ?? repoInput).trim();
    if (!clean.includes("/")) {
      setError("Format: owner/repo");
      return;
    }
    setError(null);
    try {
      await loadRepo(clean);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }

  async function handlePush() {
    if (!files.length) return;
    const message = commitMsg.trim() || `Update ${projectName} from CoCode`;
    setCommitting(true);
    setError(null);
    setLastCommitUrl(null);
    try {
      const { commitUrl } = await pushToGitHub(message);
      setLastCommitUrl(commitUrl);
      setCommitMsg("");
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setCommitting(false);
    }
  }

  async function handleCreateBranch() {
    if (!newBranch.trim()) return;
    setCreatingBranch(true);
    try {
      await createGitBranch(newBranch.trim());
      setNewBranch("");
    } catch (e) {
      setError(String(e));
    } finally {
      setCreatingBranch(false);
    }
  }

  async function handleOpenPR() {
    if (!prTitle.trim() || !github.repo) return;
    try {
      const url = await openPR(
        prTitle.trim(),
        "Generated by CoCode AI",
        github.repo.branch,
        github.repo.defaultBranch,
      );
      setPrUrl(url);
    } catch (e) {
      setError(String(e));
    }
  }

  // ── Not connected ─────────────────────────────────────────────────────────
  if (!github.connected) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-4 p-6 text-center">
        <div className="rounded-2xl border border-border bg-card/50 p-5">
          <Github className="mx-auto mb-3 size-10 text-muted-foreground/60" />
          <h3 className="mb-1 font-semibold">
            {github.needsReconnect ? "Reconnect GitHub" : "Connect GitHub"}
          </h3>
          {github.needsReconnect ? (
            <p className="mb-4 text-[13px] text-amber-400">
              Your GitHub session expired or was revoked. Sign in again to keep pushing —
              your workspace files are untouched.
            </p>
          ) : (
            <p className="mb-4 text-[13px] text-muted-foreground">
              Clone any repo, switch branches, commit, push, and open PRs — all without leaving CoCode.
            </p>
          )}
          <Button
            onClick={() => void connectGitHub()}
            disabled={github.loading}
            className="w-full"
          >
            {github.loading ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Github className="size-4" />
            )}
            {github.needsReconnect ? "Reconnect GitHub" : "Sign in with GitHub"}
          </Button>
          {github.error && !github.needsReconnect && (
            <p className="mt-2 text-[12px] text-red-400">{github.error}</p>
          )}
        </div>

        <p className="text-[11px] text-muted-foreground/50">
          Requires <code>GITHUB_CLIENT_ID</code> + <code>GITHUB_CLIENT_SECRET</code> in your environment.
        </p>
      </div>
    );
  }

  // ── Connected — no repo loaded ─────────────────────────────────────────────
  if (!github.repo) {
    return (
      <div className="flex flex-col gap-4 p-4">
        <div className="flex items-center gap-2">
          <Github className="size-4 text-foreground" />
          <span className="text-sm font-medium">GitHub</span>
          <span className="ml-auto text-[11px] text-emerald-400">Connected</span>
          <button
            type="button"
            onClick={disconnectGitHub}
            className="rounded p-1 text-muted-foreground hover:text-red-400"
            title="Disconnect"
          >
            <LogOut className="size-3.5" />
          </button>
        </div>

        {/* Repo picker */}
        <div className="rounded-xl border border-border bg-card/40 p-4">
          <div className="mb-2 flex items-center gap-1.5">
            <p className="text-[12px] font-medium">Your Repositories</p>
            <button
              type="button"
              onClick={() => void listRepos()}
              className="ml-auto rounded p-1 text-muted-foreground hover:text-foreground"
              title="Refresh repository list"
            >
              <RefreshCw className="size-3" />
            </button>
          </div>
          <select
            value=""
            onChange={(e) => e.target.value && void handleLoadRepo(e.target.value)}
            disabled={github.loading || github.repos.length === 0}
            className="w-full rounded-md border border-border bg-background/50 px-2 py-1.5 text-[12px] outline-none focus:border-primary/50 disabled:opacity-50"
          >
            <option value="" disabled>
              {github.repos.length === 0
                ? "No repositories found"
                : `Select a repository (${github.repos.length})…`}
            </option>
            {github.repos.map((r) => (
              <option key={r.fullName} value={r.fullName}>
                {r.fullName}{r.private ? " 🔒" : ""}
              </option>
            ))}
          </select>
          {github.repos.length === 0 && (
            <p className="mt-1.5 text-[11px] text-muted-foreground/60">
              No repositories on this GitHub account yet — create one on GitHub first,
              then hit refresh. CoCode never creates repos on its own.
            </p>
          )}

          <p className="mb-1 mt-3 text-[11px] text-muted-foreground/60">Or load by name:</p>
          <div className="flex gap-2">
            <input
              type="text"
              value={repoInput}
              onChange={(e) => setRepoInput(e.target.value)}
              placeholder="owner/repo"
              onKeyDown={(e) => e.key === "Enter" && void handleLoadRepo()}
              className="flex-1 rounded-md border border-border bg-background/50 px-2 py-1.5 text-[12px] outline-none focus:border-primary/50"
            />
            <Button
              size="sm"
              onClick={() => void handleLoadRepo()}
              disabled={github.loading}
            >
              {github.loading ? <Loader2 className="size-3.5 animate-spin" /> : "Load"}
            </Button>
          </div>
          {github.loading && cloneProgress > 0 && cloneProgress < 100 && (
            <div className="mt-2">
              <div className="h-1 w-full rounded-full bg-white/10">
                <div
                  className="h-full rounded-full bg-primary transition-all"
                  style={{ width: `${cloneProgress}%` }}
                />
              </div>
              <p className="mt-1 text-center text-[11px] text-muted-foreground/60">
                Loading files… {cloneProgress}%
              </p>
            </div>
          )}
          {error && <p className="mt-1.5 text-[12px] text-red-400">{error}</p>}
        </div>
      </div>
    );
  }

  // ── Connected + repo loaded ───────────────────────────────────────────────
  const { repo } = github;

  return (
    <div className="flex flex-col gap-3 overflow-y-auto p-4">
      {/* Repo header */}
      <div className="flex items-center gap-2 rounded-xl border border-border bg-card/40 p-3">
        <Github className="size-4 shrink-0" />
        <div className="min-w-0 flex-1">
          <p className="truncate text-[13px] font-medium">{repo.fullName}</p>
          <p className="text-[11px] text-muted-foreground">{repo.branch}</p>
        </div>
        <button
          type="button"
          onClick={() => void loadRepo(repo.fullName, repo.branch)}
          className="rounded p-1.5 text-muted-foreground hover:text-foreground"
          title="Refresh"
        >
          <RefreshCw className="size-3.5" />
        </button>
        <button
          type="button"
          onClick={disconnectGitHub}
          className="rounded p-1.5 text-muted-foreground hover:text-red-400"
          title="Disconnect"
        >
          <LogOut className="size-3.5" />
        </button>
      </div>

      {/* Protected branch warning */}
      {repo.protected && (
        <div className="flex items-center gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-[12px] text-amber-400">
          <ShieldAlert className="size-3.5 shrink-0" />
          Protected branch — commits will fail. Switch to a feature branch first.
        </div>
      )}

      {/* Branch switcher */}
      <div className="rounded-xl border border-border bg-card/40 p-3">
        <div className="mb-2 flex items-center gap-1.5">
          <GitBranch className="size-3.5 text-muted-foreground" />
          <span className="text-[12px] font-medium">Branches</span>
          <span className="ml-1 rounded bg-primary/20 px-1.5 py-0.5 text-[10px] text-primary">{repo.branch}</span>
        </div>
        <select
          value={repo.branch}
          onChange={(e) => void switchBranch(e.target.value)}
          className="w-full rounded-md border border-border bg-background/50 px-2 py-1.5 text-[12px] outline-none focus:border-primary/50"
        >
          {repo.branches.map((b) => (
            <option key={b} value={b}>{b}</option>
          ))}
        </select>

        <div className="mt-2 flex gap-2">
          <input
            type="text"
            value={newBranch}
            onChange={(e) => setNewBranch(e.target.value)}
            placeholder="new-branch-name"
            className="flex-1 rounded-md border border-border bg-background/50 px-2 py-1.5 text-[12px] outline-none focus:border-primary/50"
          />
          <Button
            size="sm"
            variant="secondary"
            onClick={() => void handleCreateBranch()}
            disabled={creatingBranch || !newBranch.trim()}
          >
            {creatingBranch ? <Loader2 className="size-3.5 animate-spin" /> : <Plus className="size-3.5" />}
            Branch
          </Button>
        </div>
      </div>

      {/* Commit & Push */}
      <div className="rounded-xl border border-border bg-card/40 p-3">
        <div className="mb-2 flex items-center gap-1.5">
          <GitCommit className="size-3.5 text-muted-foreground" />
          <span className="text-[12px] font-medium">Commit & Push</span>
          {dirtyFiles.length > 0 && (
            <span className="ml-auto rounded-full bg-amber-500/20 px-1.5 text-[10px] text-amber-400">
              {dirtyFiles.length} changed
            </span>
          )}
        </div>

        {files.length === 0 ? (
          <p className="text-[12px] text-muted-foreground/60">Workspace is empty — nothing to push.</p>
        ) : (
          <>
            {dirtyFiles.length > 0 && (
              <div className="mb-2 max-h-24 overflow-y-auto rounded-md border border-border/50 bg-background/20 px-2 py-1">
                {dirtyFiles.map((f) => (
                  <div key={f} className="truncate font-mono text-[11px] text-amber-400">{f}</div>
                ))}
              </div>
            )}
            <input
              type="text"
              value={commitMsg}
              onChange={(e) => setCommitMsg(e.target.value)}
              placeholder={`Commit message (default: "Update ${projectName} from CoCode")`}
              onKeyDown={(e) => e.key === "Enter" && void handlePush()}
              className="mb-2 w-full rounded-md border border-border bg-background/50 px-2 py-1.5 text-[12px] outline-none focus:border-primary/50"
            />
            <Button
              size="sm"
              className="w-full"
              onClick={() => void handlePush()}
              disabled={committing || repo.protected}
            >
              {committing ? (
                <Loader2 className="size-3.5 animate-spin" />
              ) : (
                <GitCommit className="size-3.5" />
              )}
              {committing
                ? "Pushing…"
                : `Push ${files.length} file${files.length !== 1 ? "s" : ""} (one commit)`}
            </Button>
            {lastCommitUrl && (
              <div className="mt-2 flex items-center gap-2 rounded-lg bg-emerald-500/10 px-3 py-2 text-[12px] text-emerald-400">
                <Check className="size-3.5 shrink-0" />
                <span>Pushed!</span>
                <a
                  href={lastCommitUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="ml-auto inline-flex items-center gap-1 underline hover:text-emerald-300"
                >
                  View commit <ExternalLink className="size-3" />
                </a>
              </div>
            )}
          </>
        )}
      </div>

      {/* Pull Request */}
      <div className="rounded-xl border border-border bg-card/40 p-3">
        <div className="mb-2 flex items-center gap-1.5">
          <GitPullRequest className="size-3.5 text-muted-foreground" />
          <span className="text-[12px] font-medium">Open Pull Request</span>
        </div>
        {prUrl ? (
          <div className="flex items-center gap-2 rounded-lg bg-emerald-500/10 px-3 py-2 text-[12px] text-emerald-400">
            <Check className="size-3.5" />
            <a href={prUrl} target="_blank" rel="noopener noreferrer" className="underline">
              PR opened →
            </a>
          </div>
        ) : (
          <div className="flex gap-2">
            <input
              type="text"
              value={prTitle}
              onChange={(e) => setPrTitle(e.target.value)}
              placeholder="PR title…"
              className="flex-1 rounded-md border border-border bg-background/50 px-2 py-1.5 text-[12px] outline-none focus:border-primary/50"
            />
            <Button size="sm" variant="secondary" onClick={() => void handleOpenPR()}>
              Open PR
            </Button>
          </div>
        )}
        <p className="mt-1.5 text-[11px] text-muted-foreground/50">
          {repo.branch} → {repo.defaultBranch}
        </p>
      </div>

      {error && (
        <p className="rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-[12px] text-red-400">
          {error}
        </p>
      )}
    </div>
  );
}
