// Documentation Engine — generates a README for the produced files.
//
// Runs after a successful build (normal/pro modes). Reads the generated files
// and the architecture decision, then writes a concise, accurate README.md so
// shipped code is never undocumented. Returns CodeFile[] that get merged into
// the session output (and included in /export).

import type { LLMCall, Blackboard, CodeFile } from '../types.js';
import { parseCodeBlocks } from './agents.js';

const DOCUMENTER_SYS = `You are the Documenter agent in Coagentix (TMAP v2).
Write a single, concise README.md for the project that was just generated.

Output EXACTLY one fenced block:
\`\`\`path=README.md
<full README content>
\`\`\`

The README must include, only where relevant:
- Title and one-line description
- Features (bullet list, derived from the actual files)
- Project structure (the real file list)
- How to run / open it
- Notes on tech stack

Be accurate to the provided files. Do NOT invent commands or dependencies that
aren't implied by the files. Keep it tight — no filler. No text outside the block.

Write the README prose in the SAME LANGUAGE the user wrote the task in
(Thai task → Thai README). Keep file paths, code, commands and the "path=README.md"
info string exactly as-is.`;

export async function runDocumenter(
  call: LLMCall, bb: Blackboard,
): Promise<CodeFile[]> {
  if (!bb.files.length) return [];

  const fileList = bb.files.map((f) => `- ${f.path}`).join('\n');
  // Give the model a bounded peek at each file so the README is grounded
  const excerpts = bb.files
    .slice(0, 12)
    .map((f) => `### ${f.path}\n${(f.content || '').slice(0, 600)}`)
    .join('\n\n');

  const userParts = [
    `Task: ${bb.task}`,
    bb.architect?.approach ? `Design approach: ${bb.architect.approach}` : '',
    bb.architect?.techStack ? `Tech stack: ${bb.architect.techStack}` : '',
    `Generated files (${bb.files.length}):\n${fileList}`,
    `File excerpts:\n${excerpts}`,
  ].filter(Boolean);

  const raw = await call([
    { role: 'system', content: DOCUMENTER_SYS },
    { role: 'user', content: userParts.join('\n\n') },
  ], { temperature: 0.2, maxTokens: 1500 });

  const docs = parseCodeBlocks(raw).filter((f) => /readme/i.test(f.path) || /\.md$/i.test(f.path));
  // Guard: if the model returned nothing usable, synthesise a minimal README
  if (!docs.length) {
    return [{
      path: 'README.md',
      language: 'markdown',
      content: fallbackReadme(bb),
    }];
  }
  return docs.map((d) => ({ ...d, path: d.path.split('/').pop() || 'README.md', language: 'markdown' }));
}

function fallbackReadme(bb: Blackboard): string {
  const lines = [
    `# ${bb.task.slice(0, 60)}`,
    '',
    bb.architect?.approach || 'Generated by Coagentix (TMAP v2 multi-agent pipeline).',
    '',
    '## Files',
    ...bb.files.map((f) => `- \`${f.path}\``),
    '',
  ];
  if (bb.architect?.techStack) {
    lines.push('## Tech Stack', '', bb.architect.techStack, '');
  }
  return lines.join('\n');
}
