name: Enable GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  enable:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
